[components]

target_pos = { type = "Vec2", name = "target_pos", description = "target_pos", attributes = [
    "Debuggable",
    "Networked",
] }

spawn_timer = { type = "F32", name = "spawn_timer", description = "How many seconds are left before creeps are spawned", attributes = [
    "Debuggable",
    "Resource",
]}

is_creep = { type = "Empty", name = "is_creep", description = "a creep, a NPC that is on the side of one of the teams", attributes = [
    "Debuggable",
] }

team = { type = "U32", name = "Team", description = "0=>Mars, 1=>Jupiter, 2=>... As role seems to be made for heroes, team is a more generic component for creeps.", attributes = [
    "Debuggable",
    "Networked",
]}

creep_current_state = { type = "U16", name = "creep_current_state", description = "Stores the creep current state. Check what each number is equal to each state on server.rs constants.", attributes = [
    "Debuggable",
]}

creep_next_state = { type = "U16", name = "creep_next_state", description = "Stores the creep next state.", attributes = [
    "Debuggable",
]}

pursuit_target = { type = "EntityId", name = "pursuit_target", description = "target for the creep to pursuit in its pursuit state", attributes = [
    "Debuggable",
]}
