[components]

anim_model = { type = "EntityId", name = "anim_model", description = "anim_model", attributes = [
    "Debuggable",
    "Networked",
] }

target_pos = { type = "Vec2", name = "target_pos", description = "target_pos", attributes = [
    "Debuggable",
    "Networked",
] }

is_creep = { type = "EntityId", name = "is_creep", description = "a creep, a NPC that is on the side of one of the teams", attributes = [
    "Debuggable",
] }